<div class="row" data-item-price="9.99" data-total-price="11.23">
    <div class="col-sm-2">
        <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=99%C3%9799&w=99&h=99" class="img-rounded"/>
    </div>
    <div class="col-sm-8">
        <h3>This is a product title</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius auctor erat a placerat.
            Nunc congue, lacus id commodo blandit, ex tortor blandit orci, nec euismod nisl lectus a sapien.
            Vivamus porta neque vel finibus ullamcorper. Donec tincidunt mi quis auctor convallis. Nullam
            imperdiet nisl.
        </p>
    </div>
    <div class="col-sm-2">
        From &pound;9.99<br /><small class="text-muted">+&pound;1.24 delivery</small>

        <button type="button" class="btn btn-primary">Buy Now</button>
    </div>

</div>