<div class="row" data-item-price="<?= $this->price_excl_shipping ?>" data-total-price="<?= ($this->price_excl_shipping + $this->shipping_price) ?>"<?php
    echo ' data-type=\'', \Zend\Json\Json::encode($this->type), '\'';
    foreach($this->attributes as $product_type => $attribute_value_array) :
        foreach($attribute_value_array as $attribute_name => $attribute_label_value) :
            echo ' data-attribute-'.$this->Data()->sanitize($product_type) .'-'. $this->Data()->sanitize($attribute_name) .'="'. strtolower($attribute_label_value['value']) .'"';
        endforeach;
    endforeach; ?>>
    <div class="col-sm-2">
        <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=99%C3%9799&w=99&h=99" class="img-rounded"/>
    </div>
    <div class="col-sm-8">
        <h3><?= $this->escapeHtml($this->title) ?></h3>
        <p>
            <?= $this->escapeHtml($this->description) ?>
        </p>
    </div>
    <div class="col-sm-2">
        From <?= $this->currencyFormat($this->price_excl_shipping, 'GBP'); ?><br /><small class="text-muted"><?php
            if ($this->shipping_price > 0) :
                echo '+', $this->currencyFormat($this->shipping_price, 'GBP'), ' ', $this->translate('delivery');
            else :
                echo $this->translate('FREE delivery');
            endif; ?></small>

        <button type="button" class="btn btn-primary"><?= $this->translate('Buy Now') ?></button>
    </div>

</div>