<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->Cdn()->basePath('/css/style.css'))
                        ->prependStylesheet($this->Cdn()->basePath('/css/bootstrap-theme.min.v303.css'))
                        ->prependStylesheet($this->Cdn()->basePath('/css/bootstrap.min.v303.css'))
                        ->prependStylesheet($this->Cdn()->basePath('/css/jquery-ui.lightness.min.v1114.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->Cdn()->basePath('/js/jquery-ui.min.v1114.js'))
            ->prependFile($this->Cdn()->basePath('/js/bootstrap.min.v303.js'))
            ->prependFile($this->Cdn()->basePath('/js/jquery.min.v111.js'))
            ->prependFile($this->Cdn()->basePath('/js/respond.min.v110.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->Cdn()->basePath('/js/html5shiv.min.v372.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by fonebling.co.uk. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
