<?php
/**
 * Created by PhpStorm.
 * User: Mark
 * Date: 10/08/2015
 * Time: 20:32
 */?>
<div class="row" id="page__collection">

    <div class="col-sm-4">
        <h2>Filters</h2>
        <p><small><label><input type="radio" name="bundles" value="include" checked="checked" /> Include Bundles</label> <label><input type="radio" name="bundles" value="exclude" /> Exclude Bundles</label></small></p>
        <p>
            <label for="amount">Price range:</label>
            <div id="amount"></div>
        </p>

        <div id="slider-range"></div>

        <?php $attributes = array(
                'colour' => 'Colour',
                'type' => 'Product Type',
            );
        $options = [];
        foreach($attributes as $index => $label) {
            $options[$index] = $this->Data()->asJsonArray($this->products, '[0-9]+.attributes.'. $index);
            echo '<h4>', $label, '</h4>';
            echo '<ol>';
            $array = array_count_values(json_decode($options[$index]));
            foreach($array as $variant => $count) :
                echo '<li>', $variant, ' (', $count, ')', '</li>';
            endforeach;
            echo '</ol>';
        }
         ?>


    </div>
    <div class="col-sm-8 collection" data-total-price="<?= $this->Data()->asJsonArray($this->products, '[0-9]+.price_incl_shipping') ?>"<?php
     foreach($options as $label => $value) :
        echo " data-attributes-", $label ,"='", $value, "'";
     endforeach; ?>>
        <?php echo $this->partialLoop('application\_partials\product.phtml', $this->Data()->asArray($this->products)) ?>
    </div>


</div>


<?php $this->inlineScript()->captureStart();
echo <<<JS
$(function() {
    var prices = $('.collection').data('total-price');

    var min_price = Math.min.apply(Math,prices);
    var max_price = Math.max.apply(Math,prices);
    $( "#slider-range" ).slider({

        range: true,
        min: min_price,
        max: max_price,
        values: [ min_price , max_price ],
        animate: true,
        slide: function( event, ui ) {
            $( "#amount" ).html( "&pound;" + ui.values[ 0 ] + " - &pound;" + ui.values[ 1 ] );
        }

    });
    $( "#amount" ).html( "&pound;" + $( "#slider-range" ).slider( "values", 0 ) +
      " - &pound;" + $( "#slider-range" ).slider( "values", 1 ) );
  });
JS;
$this->inlineScript()->captureEnd(); ?>