<?php
/**
 * Created by PhpStorm.
 * User: Mark
 * Date: 10/08/2015
 * Time: 20:32
 */?>
<div class="row" id="page__collection">

    <div class="col-sm-4" id="collection__filters">
        <h2>Filters</h2>
        <p><small><label><input type="radio" name="bundles" value="include" checked="checked" /> Include Bundles</label> <label><input type="radio" name="bundles" value="exclude" /> Exclude Bundles</label></small></p>
        <p>
            <label for="amount">Price range:</label>
            <span id="amount"></span>
        </p>

        <input type="hidden" name="filter_min_price" id="filter_min_price" value=""/>
        <input type="hidden" name="filter_max_price" id="filter_max_price" value=""/>

        <div id="slider-range"></div>

        <?php
        echo '<h4>Product Types</h4>';
            echo $this->Navigation()->setProducts($this->products)->productTypes();
         ?>


    </div>
    <div class="col-sm-8 collection" data-total-price="<?= $this->json($this->Data()->getKeyValue($this->products, '[0-9]+.price_incl_shipping')) ?>">
        <?php echo $this->partialLoop('application\_partials\product.phtml', $this->Data()->asArray($this->products)) ?>
    </div>


</div>


<?php $this->inlineScript()->captureStart();
echo <<<JS
$(function() {
    var prices = $('.collection').data('total-price');

    var min_price = Math.floor(Math.min.apply(Math,prices));
    var max_price = Math.ceil(Math.max.apply(Math,prices));

    $( "#slider-range" ).slider({

        range: true,
        min: min_price,
        max: max_price,
        values: [ min_price , max_price ],
        animate: true,
        slide: function( event, ui ) {
            var low =  ui.values[ 0 ];
            var high =  ui.values[ 1 ];
            $( "#amount" ).html( "&pound;" + low + " - &pound;" + high );
            $( "#filter_min_price" ).val( low );
            $( "#filter_max_price" ).val( high );

            var list = [];
            for (var i = low; i <= high; i++) {
                list.push(i);
            }

        filter();
        }

    });
    $( "#filter_min_price" ).val( min_price );
    $( "#filter_max_price" ).val( max_price );
    $( "#amount" ).html( "&pound;" + min_price +
      " - &pound;" + max_price );

      filter();
  });

  function filter()
  {

        $('.collection').find('.row').each(function( index ) {
            var row = $(this);

            /** PRICE **/
            if (($(row).data('total-price') >= parseInt($('#filter_min_price').val()) + '.00' && $(row).data('total-price') <= parseInt($('#filter_max_price').val()) + '.00')) {
                $(row).show();
            } else {
                $(row).hide();
            }
        });

  }
JS;
$this->inlineScript()->captureEnd(); ?>