<div class="row" id="page__homepage">



    <h1>Welcome to fonebling.co.uk</h1>


    <h2>Choose the manufacturer of your device</h2>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container apple">
                <div class="brand__link"><a href="/collections/apple">Apple Accessories</a></div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container samsung">
            <div class="brand__link"><a href="/collections/samsung">Samsung Accessories</a></div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container htc">
            <div class="brand__link"><a href="/collections/htc">HTC Accessories</a></div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container sony">
            <div class="brand__link"><a href="/collections/sony">Sony Accessories</a></div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container nokia">
            <div class="brand__link"><a href="/collections/samsung">Nokia Accessories</a></div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 brand">
        <div class="brand__container motorola">
            <div class="brand__link"><a href="/collections/motorola">Motorola Accessories</a></div>
        </div>
    </div>
    <div class="span12 border-bottom p30"></div>




</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$('#page__homepage').on('click', '.brand', function(e) {
    e.preventDefault();
    var container = $(this);

    window.location.href=$(container).find('a').prop('href');
})
JS;
$this->inlineScript()->captureEnd(); ?>